### ISSUE TITLE
Error log found in s1 service

### ISSUE THREAD

**Issue by wilsonoen** [scp756-221/term-project-raccoon-fury#47]

**Comment by wilsonoen** [comment]
Running `tools/gatling-50-user.sh` causes following error in cmpt756s1 service.

127.0.0.6 - - [01/Apr/2022 23:38:37] "GET /api/v1/user/75ebc062-a808-4a0f-a79b-8ac568564bfe HTTP/1.1" 200 -                                                                      
127.0.0.6 - - [01/Apr/2022 23:38:37] "GET /api/v1/user/b66f61e7-4fad-402f-aaad-101e3e2522d3 HTTP/1.1" 200 -                                                                      
[2022-04-01 23:38:37,266] ERROR in app: Exception on /api/v1/user/b66f61e7-4fad-402f-aaad-101e3e2522d3 [GET]                                                                     
Traceback (most recent call last):                                                                                                                                               
File "/opt/bitnami/python/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app                                                                                    
response = self.full_dispatch_request()                                                                                                                                      
File "/opt/bitnami/python/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request                                                                       
rv = self.handle_user_exception(e)                                                                                                                                           
File "/opt/bitnami/python/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception                                                                       
reraise(exc_type, exc_value, tb)                                                                                                                                             
File "/opt/bitnami/python/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise                                                                                   
raise value                                                                                                                                                                  
File "/opt/bitnami/python/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request                                                                       
rv = self.dispatch_request()                                                                                                                                                 
File "/opt/bitnami/python/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request                                                                            
return self.view_functions[rule.endpoint](**req.view_args)                                                                                                                   
File "app.py", line 138, in get_user                                                                                                                                           
return (response.json())                                                                                                                                                     
File "/opt/bitnami/python/lib/python3.8/site-packages/requests/models.py", line 898, in json                                                                                   
return complexjson.loads(self.text, **kwargs)                                                                                                                                
File "/opt/bitnami/python/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads                                                                              
return _default_decoder.decode(s)                                                                                                                                            
File "/opt/bitnami/python/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode                                                                              
obj, end = self.raw_decode(s)                                                                                                                                                
File "/opt/bitnami/python/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode                                                                          
return self.scan_once(s, idx=_w(s, idx).end())                                                                                                                               
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                                                                                     
127.0.0.6 - - [01/Apr/2022 23:38:37] "GET /api/v1/user/b66f61e7-4fad-402f-aaad-101e3e2522d3 HTTP/1.1" 500 -                                                                      
127.0.0.6 - - [01/Apr/2022 23:38:37] "GET /api/v1/user/2e4c0d7e-b0e6-4739-b044-ee1d45872a7c HTTP/1.1" 200 -                                                                      
127.0.0.6 - - [01/Apr/2022 23:38:37] "GET /api/v1/user/423a10a6-ab66-48c5-a1c7-dffb3169d744 HTTP/1.1" 200 -

**Comment by wilsonoen** [comment]
Error is caused by DyanmoDB ProvisionedThroughputExceededException. 
Closed the issue without any code change
